version: 0.1.0-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\wustc

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - cargo build --verbose --release
  -
  - cp target\release\wustc.exe wustc-v0.1.0.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note wustc-v0.1.0.exe

test: off

artifacts:
  - path: wustc-v0.1.0.exe

deploy:
  provider: GitHub
  artifact: wustc-v0.1.0.exe
  auth_token:
    secure: Nt1iLmqM1zjylvp9ACEUOZyRnApF+hVdICEFq9VE0PWYVGZh/hoXdlw1AgIIrVxI
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
