max_width             = 160
ideal_width           = 128
fn_call_width         = 96
fn_args_paren_newline = false
fn_args_density       = "Compressed"
struct_trailing_comma = "Always"
wrap_comments         = true
